[eMule]
AppVersion=2.3.3
Nick=${HOSTNAME}
QueueSizePrecent=10
MaxUpload=0
MaxDownload=0
SlotAllocation=2
Port=4662
UDPPort=4672
UDPEnabled=1
MaxConnections=500
MaxSourcesPerFile=300
TempDir=${AMULE_HOME}/Temp
IncomingDir=${AMULE_HOME}/Incoming
UPnPEnabled=0

[ExternalConnect]
AcceptExternalConnections=1
ECAddress=0.0.0.0
ECPort=4712
ECPassword=${AMULE_PASS_MD5}

[WebServer]
Enabled=1
Password=${AMULE_WEB_PASS_MD5}
PasswordLow=
Port=4711
PageRefresh=5
UseGzip=1
UseLowRightsUser=0
Title=aMule Web Server @ ${HOSTNAME}
Template=default
UseSSL=0
# Nota: Para SSL real, usar Reverse Proxy (Nginx) frente al puerto 4711.

[GUI]
# GUI desactivada para modo daemon

[Proxy]
ProxyEnable=0