# /etc/rsyncd.conf configuration file
# Configuración Gestionada por Confiraspa (v1.0 Final)

# --- Global Settings ---
uid = ${ARR_USER}
gid = ${ARR_GROUP}
use chroot = yes
max connections = 10
pid file = /var/run/rsyncd.pid
log file = /var/log/rsync.log
transfer logging = yes
timeout = 300
# Evita problemas de mapeo de usuarios entre distintos sistemas (Mac/Linux/Windows)
numeric ids = yes

# --- Modules ---

[Backup]
    path = ${PATH_BACKUP}
    comment = Disco de Copias de Seguridad (NAS)
    read only = no
    list = yes
    # Seguridad LAN
    hosts allow = 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
    hosts deny = *
    # Optimización CPU
    dont compress = *.gz *.tgz *.zip *.z *.Z *.rpm *.deb *.bz2 *.mp4 *.mkv *.avi *.jpg

[Descargas]
    path = ${DIR_TORRENTS}
    comment = Carpeta de Descargas Completadas
    read only = yes
    hosts allow = 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8