[global]
    workgroup = ${SMB_WORKGROUP}
    server string = Raspberry Pi NAS
    security = user
    map to guest = Bad User
    dns proxy = no
    log file = /var/log/samba/log.%m
    max log size = 1000
    
    # Optimizaciones NAS para RPi
    socket options = TCP_NODELAY IPTOS_LOWDELAY
    use sendfile = true
    aio read size = 16384
    aio write size = 16384
    vfs objects = catia fruit streams_xattr

[Descargas]
    comment = Disco Duro - Descargas Completas
    path = ${DIR_TORRENTS}
    browseable = yes
    read only = no
    valid users = ${SMB_USER} @media
    force group = media
    create mask = 0775
    directory mask = 0775

[WDElements]
    comment = Biblioteca Multimedia Completa
    path = ${PATH_LIBRARY}
    browseable = yes
    read only = no
    valid users = ${SMB_USER} @media
    force group = media
    create mask = 0775
    directory mask = 0775

[Backup]
    comment = Disco de Copias de Seguridad
    path = ${PATH_BACKUP}
    browseable = yes
    read only = no
    valid users = ${SMB_USER} @media
    force group = media
    create mask = 0775
    directory mask = 0775